version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gw_backend
      POSTGRES_PASSWORD: THIS_IS_NOT_A_PRODUCTION_PASSWORD
      POSTGRES_DB: gw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    # depends_on: #this takes forever on COBALT
    #   - db
    environment:
      DATABASE_URL: postgresql://gw_backend:THIS_IS_NOT_A_PRODUCTION_PASSWORD@db:5432/gw
    ports:
      - "8000:8000"
  # frontend: # no frontend yet so we don't need to start and stop it everytime we make a change
  #   build: ./frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"

volumes:
  pgdata:

